train_file: ['../dataSet/downstream_json/nlvr_train.json']
val_file: ['../dataSet/downstream_json/nlvr_dev.json']
test_file: ['../dataSet/downstream_json/nlvr_test.json']

image_root: '../dataSet/nlvr2'  #NLVR2-images/ 

image_res: 384
second_input_size: 384
vision_width: 1024
embed_dim: 256
batch_size_train: 10

bert_config: 'configs/config_bert.json'

max_length: 25
num_beams: 1
temperature: 1
top_k: 0
top_p: 1
repetition_penalty: 1
length_penalty: 1
early_stopping: false
num_return_sequences: 1
init_encoder: False
init_decoder: False
last_hidden_id_shift: 1

# dalle
discrete_vae_weight_path: "pretrained"
discrete_vae_type: "vqgan"

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.0}
schedular: {sched: linear, last_epoch: -1, epochs: 9, warmup_epochs: 1}






